// ─────────────── data.js — All static data (brands, tires, wheels, packages, locations, categories)
window.CWD_DATA = {
  BRAND_CDN: 'https://storage.googleapis.com/autosync-brand-logos/logos/',
  VEH_CDN: 'https://storage.googleapis.com/autosync-brand-logos/vehicles/',

  // These will be populated from the API; static fallbacks below
  brands: [
    { name:'Michelin',    slug:'Michelin'    }, { name:'Bridgestone', slug:'Bridgestone' },
    { name:'Goodyear',    slug:'Goodyear'    }, { name:'Continental', slug:'Continental' },
    { name:'Pirelli',     slug:'Pirelli'     }, { name:'Falken',      slug:'Falken'      },
    { name:'Hankook',     slug:'Hankook'     }, { name:'Yokohama',    slug:'Yokohama'    },
    { name:'Cooper',      slug:'Cooper'      }, { name:'Toyo',        slug:'Toyo'        },
    { name:'Nitto',       slug:'Nitto'       }, { name:'BFGoodrich',  slug:'Bfgoodrich'  },
  ].map(function(b) { return Object.assign({}, b, { logo: 'https://storage.googleapis.com/autosync-brand-logos/logos/' + b.slug + '.webp' }); }),

  wheelBrandList: [
    { name:'Vossen' }, { name:'HRE' }, { name:'Enkei' }, { name:'BBS' }, { name:'Rotiform' },
    { name:'Niche' }, { name:'TSW' }, { name:'Konig' }, { name:'Method' }, { name:'Fuel' },
    { name:'Motegi' }, { name:'American Racing' },
  ],
  wheelBrands: ['Vossen','HRE','Enkei','BBS','Rotiform','Niche','TSW','Konig','Method','Fuel','Motegi','American Racing'],

  vehicleMakes: [
    'Acura','Audi','BMW','Buick','Cadillac','Chevrolet','Chrysler','Dodge','Ford',
    'GMC','Honda','Hyundai','Infiniti','Jeep','Kia','Lexus','Lincoln',
    'Mazda','Mercedes-Benz','Nissan','Ram','Subaru','Tesla','Toyota','Volkswagen',
  ].map(function(m) { return { name: m, logo: 'https://storage.googleapis.com/autosync-brand-logos/vehicles/' + m.replace(/[\s-]/g,'_') + '.webp' }; }),

  // Static fallback tires (used if API fails)
  _staticTires: [
    { id:'t-mich-ps4s-245-40-20',   brand:'Michelin',    model:'Pilot Sport 4S',         size:'245/40R20', season:'Summer',     load:'99Y', warranty:30000,  priceEach:389, rating:4.9, reviews:612, runFlat:false },
    { id:'t-mich-cc2-235-50-19',    brand:'Michelin',    model:'CrossClimate2',          size:'235/50R19', season:'All-Weather',load:'103V',warranty:60000,  priceEach:268, rating:4.9, reviews:1240, runFlat:false },
    { id:'t-mich-dh-235-55-18',     brand:'Michelin',    model:'Defender 2',             size:'235/55R18', season:'All-Season', load:'100H',warranty:85000,  priceEach:219, rating:4.9, reviews:890, runFlat:false },
    { id:'t-bfg-ko2-285-70-17',     brand:'BFGoodrich',  model:'All-Terrain T/A KO2',    size:'285/70R17', season:'All-Terrain',load:'121R',warranty:50000,  priceEach:329, rating:4.8, reviews:2140, runFlat:false },
    { id:'t-bfg-advantage-215-55-17',brand:'BFGoodrich', model:'Advantage T/A Sport LT', size:'215/55R17', season:'All-Season', load:'94V', warranty:65000,  priceEach:149, rating:4.6, reviews:420, runFlat:false },
    { id:'t-brid-ws90-235-45-18',   brand:'Bridgestone', model:'Blizzak WS90',           size:'235/45R18', season:'Winter',     load:'94H', warranty:0,      priceEach:198, rating:4.8, reviews:980, runFlat:false },
    { id:'t-brid-pot-245-40-19',    brand:'Bridgestone', model:'Potenza Sport',          size:'245/40R19', season:'Summer',     load:'98Y', warranty:20000,  priceEach:289, rating:4.7, reviews:310, runFlat:false },
    { id:'t-good-ec2-245-45-19',    brand:'Goodyear',    model:'Eagle Exhilarate',       size:'245/45R19', season:'UHP All-Season',load:'102Y',warranty:45000,priceEach:238, rating:4.7, reviews:520, runFlat:false },
    { id:'t-good-wd-275-65-18',     brand:'Goodyear',    model:'Wrangler DuraTrac',      size:'275/65R18', season:'All-Terrain',load:'116S',warranty:50000,  priceEach:298, rating:4.7, reviews:1420, runFlat:false },
    { id:'t-cont-dws-245-45-19',    brand:'Continental', model:'ExtremeContact DWS06+',  size:'245/45R19', season:'UHP All-Season',load:'102Y',warranty:50000,priceEach:249, rating:4.8, reviews:1880, runFlat:false },
    { id:'t-cont-purecontact-235-55-17',brand:'Continental',model:'PureContact LS',      size:'235/55R17', season:'All-Season', load:'99H', warranty:70000,  priceEach:179, rating:4.8, reviews:690, runFlat:false },
    { id:'t-pirelli-pz4-265-40-21', brand:'Pirelli',     model:'P Zero PZ4',             size:'265/40R21', season:'Summer',     load:'105Y',warranty:0,      priceEach:489, rating:4.8, reviews:240, runFlat:false },
    { id:'t-pirelli-sz-215-55-17',  brand:'Pirelli',     model:'Scorpion Verde',         size:'215/55R17', season:'All-Season', load:'94V', warranty:65000,  priceEach:189, rating:4.7, reviews:390, runFlat:false },
    { id:'t-falken-ze001-245-45-18',brand:'Falken',      model:'Ziex ZE001 A/S',         size:'245/45R18', season:'All-Season', load:'100W',warranty:60000,  priceEach:159, rating:4.6, reviews:210, runFlat:false },
    { id:'t-falken-wildpeak-285-70-17',brand:'Falken',   model:'Wildpeak A/T3W',         size:'285/70R17', season:'All-Terrain',load:'117T',warranty:55000,  priceEach:269, rating:4.7, reviews:1620, runFlat:false },
    { id:'t-hankook-v12-235-45-18', brand:'Hankook',     model:'Ventus V12 evo2',        size:'235/45R18', season:'Summer',     load:'98Y', warranty:30000,  priceEach:179, rating:4.6, reviews:280, runFlat:false },
    { id:'t-yoko-ice-235-55-18',    brand:'Yokohama',    model:'iceGUARD iG53',          size:'235/55R18', season:'Winter',     load:'100H',warranty:0,      priceEach:188, rating:4.6, reviews:180, runFlat:false },
    { id:'t-toyo-proxes-275-40-20', brand:'Toyo',        model:'Proxes Sport',           size:'275/40R20', season:'Summer',     load:'106Y',warranty:0,      priceEach:298, rating:4.7, reviews:340, runFlat:false },
    { id:'t-toyo-opat3-265-65-18',  brand:'Toyo',        model:'Open Country A/T III',   size:'265/65R18', season:'All-Terrain',load:'114T',warranty:65000,  priceEach:278, rating:4.8, reviews:980, runFlat:false },
    { id:'t-nitto-nt555-275-35-20', brand:'Nitto',       model:'NT555 G2',               size:'275/35R20', season:'Summer',     load:'102W',warranty:0,      priceEach:269, rating:4.7, reviews:420, runFlat:false },
    { id:'t-cooper-evo-235-60-18',  brand:'Cooper',      model:'Evolution Tour',         size:'235/60R18', season:'All-Season', load:'107H',warranty:75000,  priceEach:159, rating:4.5, reviews:210, runFlat:false },
    { id:'t-mich-xice-235-55-18',   brand:'Michelin',    model:'X-Ice Snow',             size:'235/55R18', season:'Winter',     load:'104H',warranty:40000,  priceEach:229, rating:4.9, reviews:610, runFlat:false },
  ],
  tires: [], // populated from API on load

  // Static fallback wheels
  _staticWheels: [
    { id:'w-vossen-hf5-20',   brand:'Vossen',   model:'HF-5',        size:'20x9',   offset:'+32', bolt:'5x114.3', finish:'Satin Black',       type:'Flow-Formed', priceEach:519, rating:4.9, reviews:218 },
    { id:'w-vossen-hf3-19',   brand:'Vossen',   model:'HF-3',        size:'19x8.5', offset:'+35', bolt:'5x120',   finish:'Tinted Gloss Black',type:'Flow-Formed', priceEach:469, rating:4.9, reviews:162 },
    { id:'w-hre-p101-21',     brand:'HRE',      model:'P101',        size:'21x9.5', offset:'+28', bolt:'5x112',   finish:'Brushed Clear',     type:'Forged',      priceEach:1490,rating:4.9, reviews:52 },
    { id:'w-enkei-tsp5-18',   brand:'Enkei',    model:'TSP-5',       size:'18x8',   offset:'+45', bolt:'5x114.3', finish:'Matte Black',       type:'Cast',        priceEach:239, rating:4.8, reviews:480 },
    { id:'w-enkei-rpf1-17',   brand:'Enkei',    model:'RPF1',        size:'17x9',   offset:'+35', bolt:'5x114.3', finish:'F1 Silver',         type:'Flow-Formed', priceEach:329, rating:4.9, reviews:920 },
    { id:'w-bbs-ch-r-20',     brand:'BBS',      model:'CH-R II',     size:'20x9',   offset:'+25', bolt:'5x112',   finish:'Satin Platinum',    type:'Forged',      priceEach:999, rating:4.9, reviews:84 },
    { id:'w-rotiform-blq-19', brand:'Rotiform', model:'BLQ',         size:'19x8.5', offset:'+38', bolt:'5x112',   finish:'Matte Anthracite',  type:'Cast',        priceEach:279, rating:4.8, reviews:410 },
    { id:'w-niche-milan-19',  brand:'Niche',    model:'Milan M134',  size:'19x8.5', offset:'+40', bolt:'5x114.3', finish:'Gloss Black Milled',type:'Cast',        priceEach:249, rating:4.7, reviews:310 },
    { id:'w-tsw-nur-19',      brand:'TSW',      model:'N\u00fcrburgring', size:'19x8.5', offset:'+40', bolt:'5x114.3', finish:'Gunmetal',          type:'Cast',        priceEach:239, rating:4.7, reviews:260 },
    { id:'w-konig-hypergram-18',brand:'Konig',  model:'Hypergram',   size:'18x8.5', offset:'+35', bolt:'5x114.3', finish:'Metallic Carbon',   type:'Flow-Formed', priceEach:259, rating:4.8, reviews:540 },
    { id:'w-method-305-17',   brand:'Method',   model:'305 NV',      size:'17x8.5', offset:'0',   bolt:'6x139.7', finish:'Matte Black',       type:'Cast',        priceEach:289, rating:4.8, reviews:890 },
    { id:'w-fuel-rebel-18',   brand:'Fuel',     model:'Rebel D679',  size:'18x9',   offset:'+1',  bolt:'6x139.7', finish:'Matte Gunmetal',    type:'Cast',        priceEach:329, rating:4.7, reviews:620 },
    { id:'w-motegi-mr146-18', brand:'Motegi',   model:'MR146',       size:'18x8',   offset:'+42', bolt:'5x114.3', finish:'Matte Black',       type:'Cast',        priceEach:189, rating:4.6, reviews:180 },
    { id:'w-amr-tt60-18',     brand:'American Racing', model:'Torq Thrust II', size:'18x8', offset:'0', bolt:'5x114.3', finish:'Polished',    type:'Replica',     priceEach:269, rating:4.7, reviews:340 },
    { id:'w-vossen-hf2-18',   brand:'Vossen',   model:'HF-2',        size:'18x8.5', offset:'+40', bolt:'5x114.3', finish:'Silver Polished',   type:'Flow-Formed', priceEach:419, rating:4.8, reviews:140 },
    { id:'w-enkei-kojin-19',  brand:'Enkei',    model:'Kojin',       size:'19x8.5', offset:'+40', bolt:'5x114.3', finish:'Matte Black',       type:'Flow-Formed', priceEach:339, rating:4.8, reviews:210 },
  ],
  wheels: [], // populated from API on load

  packages: [
    { id:'pkg-vossen-hf5-pilotsport', name:'Vossen HF-5 \u00b7 Pilot Sport 4S', wheelBrand:'Vossen', wheelModel:'HF-5', finish:'Satin Black', tireBrand:'Michelin', tireModel:'Pilot Sport 4S', size:'20x9 \u00b7 245/40R20', price:3240, was:3640, rating:4.9, reviews:312, fit:'Performance sedan / coupe', cat:'Performance' },
    { id:'pkg-method-305-ko2',      name:'Method 305 NV \u00b7 BFG KO2',       wheelBrand:'Method',  wheelModel:'305 NV',        finish:'Matte Black', tireBrand:'BFGoodrich', tireModel:'All-Terrain T/A KO2', size:'17x8.5 \u00b7 285/70R17', price:2980, was:3280, rating:4.8, reviews:940, fit:'Truck / Off-road',        cat:'All-Terrain' },
    { id:'pkg-niche-milan-dws',     name:'Niche Milan \u00b7 ExtremeContact',  wheelBrand:'Niche',   wheelModel:'Milan M134',    finish:'Gloss Black Milled', tireBrand:'Continental', tireModel:'ExtremeContact DWS06+', size:'19x8.5 \u00b7 245/45R19', price:2740, was:2990, rating:4.8, reviews:520, fit:'Luxury sedan',        cat:'UHP All-Season' },
    { id:'pkg-fuel-rebel-duratrac', name:'Fuel Rebel \u00b7 Wrangler DuraTrac',wheelBrand:'Fuel',    wheelModel:'Rebel D679',    finish:'Matte Gunmetal', tireBrand:'Goodyear',    tireModel:'Wrangler DuraTrac',     size:'18x9 \u00b7 275/65R18',  price:3120, was:3420, rating:4.7, reviews:780, fit:'Jeep / SUV',             cat:'All-Terrain' },
    { id:'pkg-hre-p101-pzero',      name:'HRE P101 \u00b7 P Zero PZ4',         wheelBrand:'HRE',     wheelModel:'P101',          finish:'Brushed Clear',  tireBrand:'Pirelli',     tireModel:'P Zero PZ4',            size:'21x9.5 \u00b7 265/40R21', price:6880, was:7440, rating:4.9, reviews:148, fit:'Sport / Exotic',         cat:'Performance' },
    { id:'pkg-enkei-tsp5-blizzak',  name:'Enkei TSP5 \u00b7 Blizzak WS90',     wheelBrand:'Enkei',   wheelModel:'TSP-5',         finish:'Matte Black',    tireBrand:'Bridgestone', tireModel:'Blizzak WS90',          size:'18x8 \u00b7 235/45R18',  price:2480, was:2690, rating:4.8, reviews:410, fit:'Winter daily driver',    cat:'Winter' },
    { id:'pkg-tsw-nurburgring-f1',  name:'TSW N\u00fcrburgring \u00b7 Eagle F1',    wheelBrand:'TSW',     wheelModel:'N\u00fcrburgring',   finish:'Gunmetal',       tireBrand:'Goodyear',    tireModel:'Eagle F1 Asymmetric 3', size:'19x8.5 \u00b7 245/40R19', price:2640, was:0,    rating:4.7, reviews:290, fit:'Sport sedan',            cat:'Performance' },
    { id:'pkg-rotiform-blq-crossclimate', name:'Rotiform BLQ \u00b7 CrossClimate2', wheelBrand:'Rotiform', wheelModel:'BLQ', finish:'Matte Anthracite', tireBrand:'Michelin',    tireModel:'CrossClimate2',         size:'19x8.5 \u00b7 235/50R19', price:2890, was:3100, rating:4.9, reviews:612, fit:'All-weather daily',      cat:'All-Weather' },
  ],

  locations: [
    { id:'holbrook',     name:'Custom Wheel Deal', city:'Detroit',      addr:'21221 W Seven Mile Rd', zip:'48219', phone:'313-257-7777', phoneTel:'+13132577777', hours:'Mon-Fri 8-6 \u00b7 Sat 8-3' },
    { id:'roseville',    name:'Custom Wheel Deal', city:'Roseville',    addr:'32105 Gratiot Ave',     zip:'48066', phone:'586-871-1111', phoneTel:'+15868711111', hours:'Mon-Fri 8-6 \u00b7 Sat 8-3' },
    { id:'chesterfield', name:'Custom Wheel Deal', city:'Chesterfield', addr:'49765 Gratiot Ave',     zip:'48051', phone:'586-257-7778', phoneTel:'+15862577778', hours:'Mon-Fri 8-6 \u00b7 Sat 8-3' },
  ],

  categories: [
    { id:'performance', label:'Performance',  icon:'rocket_launch' },
    { id:'all-weather', label:'All-Weather',  icon:'partly_cloudy_day' },
    { id:'winter',      label:'Winter',       icon:'ac_unit' },
    { id:'all-terrain', label:'All-Terrain',  icon:'terrain' },
    { id:'truck',       label:'Truck & SUV',  icon:'local_shipping' },
    { id:'touring',     label:'Touring',      icon:'directions_car' },
  ],
};
// Initialize tires/wheels with static fallbacks
window.CWD_DATA.tires = window.CWD_DATA._staticTires.slice();
window.CWD_DATA.wheels = window.CWD_DATA._staticWheels.slice();

// ─────────────── Rebates data
window.REBATES = [
  {
    "brand": "GOODYEAR",
    "amount": 60,
    "amountReason": "Buy 4 and qualify for a $60 Rebate",
    "amountTwo": 100,
    "amountTwoReason": "Use your Goodyear Credit Card and get an additional bonus rebate of $100",
    "qtyRequired": 4,
    "startDate": "3/1/26 0:00",
    "endDate": "6/30/26 0:00",
    "description": "Get up to $180 back* on a set of 4 select Goodyear tires when you use the Goodyear Credit Card on purchases made 3/1/26 - 6/30/26 by online or mail-in rebate and paid by prepaid card or virtual card. *Subject to credit approval. Terms and conditions apply. To learn more, click \"Details\" or see store.",
    "pdfUrl": "https://www.r2cthemes.com/Rebates/2026/pdf/2026_npp1_gycc_gy_base-cc_rebate_form_final.pdf",
    "previewImage": "https://www.r2cthemes.com/Rebates/2026/goodyear-mar2026-200.webp",
    "bannerImage": "https://www.r2cthemes.com/Rebates/2026/goodyear-mar2026-300.webp"
  },
  {
    "brand": "COOPER",
    "amount": 70,
    "amountReason": "Buy 4 and qualify for a $70 Rebate",
    "amountTwo": 70,
    "amountTwoReason": "Use your Goodyear Credit Card and get an additional bonus rebate of $70",
    "qtyRequired": 4,
    "startDate": "3/1/26 0:00",
    "endDate": "6/30/26 0:00",
    "description": "Get up to $140 back* on a set of 4 select Cooper\u00ae tires when you use the Goodyear Credit Card on purchases made 3/1/26 - 6/30/26 by online or mail-in rebate and paid by prepaid card or virtual card. *Subject to credit approval. Terms and conditions apply. To learn more, click \"Details\" or see store.",
    "pdfUrl": "https://www.r2cthemes.com/Rebates/2026/pdf/2026_npp1_gycc_ct_base-cc_rebate_form_final.pdf",
    "previewImage": "https://www.r2cthemes.com/Rebates/2026/cooper-mar2026-200.webp",
    "bannerImage": "https://www.r2cthemes.com/Rebates/2026/cooper-mar2026-300.webp"
  },
  {
    "brand": "GENERAL",
    "amount": 70,
    "amountReason": "Buy 4 and qualify for a $70 Rebate",
    "amountTwo": 70,
    "amountTwoReason": "Use your General Tire Credit Card and get a bonus rebate of $70 Prepaid Card",
    "qtyRequired": 4,
    "startDate": "3/1/26 0:00",
    "endDate": "4/30/26 0:00",
    "description": "Get up to $160 via prepaid card when you buy any 4 qualifying General Tire brand tires.",
    "pdfUrl": "https://www.r2cthemes.com/Rebates/2026/pdf/plt-gt-dd-mar26-pad-syf.pdf",
    "previewImage": "https://www.r2cthemes.com/Rebates/2026/general-mar2026-200.webp",
    "bannerImage": "https://www.r2cthemes.com/Rebates/2026/general-mar2026-300.webp"
  },
  {
    "brand": "MICKEY THOMPSON",
    "amount": 100,
    "amountReason": "Buy 4 and qualify for a $100 rebate",
    "amountTwo": 0,
    "amountTwoReason": "",
    "qtyRequired": 4,
    "startDate": "3/15/26 0:00",
    "endDate": "4/30/26 0:00",
    "description": "Receive a $100 rebate when you purchase  a set of 4 qualifying Mickey Thompson tires.",
    "pdfUrl": "https://www.mickeythompsontires.com/offer/spring-rebate-2026",
    "previewImage": "https://www.r2cthemes.com/Rebates/2026/mickey-mar2026-200.webp",
    "bannerImage": "https://www.r2cthemes.com/Rebates/2026/mickey-mar2026-300.webp"
  },
  {
    "brand": "PIRELLI",
    "amount": 100,
    "amountReason": "Buy 4 and qualify for a $100 Rebate",
    "amountTwo": 0,
    "amountTwoReason": "",
    "qtyRequired": 4,
    "startDate": "4/7/26 0:00",
    "endDate": "4/20/26 0:00",
    "description": "Get a $100 rebate when you purchase a new set of four (4) P7 AS PLUS 3 or CINTURATO P7 ALL SEASON tires.",
    "pdfUrl": "https://www.r2cthemes.com/Rebates/2026/pdf/april_2026_us_consumer_rebate_form_mail-in.pdf",
    "previewImage": "https://www.r2cthemes.com/Rebates/2026/pirelli-apr2026-200.webp",
    "bannerImage": "https://www.r2cthemes.com/Rebates/2026/pirelli-apr2026-300.webp"
  },
  {
    "brand": "HANKOOK",
    "amount": 100,
    "amountReason": "Buy 4 and qualify for a $100 Rebate",
    "amountTwo": 0,
    "amountTwoReason": "",
    "qtyRequired": 4,
    "startDate": "4/20/26 0:00",
    "endDate": "5/31/26 0:00",
    "description": "Get a $100 rebate when you buy a set of 4 select Hankook Tires.",
    "pdfUrl": "https://hankookrebates.com/",
    "previewImage": "https://www.r2cthemes.com/Rebates/2026/hankook-apr2026-200.webp",
    "bannerImage": "https://www.r2cthemes.com/Rebates/2026/hankook-apr2026-300.webp"
  },
  {
    "brand": "BFGOODRICH",
    "amount": 80,
    "amountReason": "Buy 4 and qualify for an $80 Rebate",
    "amountTwo": 0,
    "amountTwoReason": "",
    "qtyRequired": 4,
    "startDate": "3/26/26 0:00",
    "endDate": "5/23/26 0:00",
    "description": "Get $80 via Visa\u00ae Reward Card or Visa\u00ae Virtual Account after online submission on purchases of four (4) new BFGoodrich passenger or light truck tires.",
    "pdfUrl": "https://www.r2cthemes.com/Rebates/2026/pdf/bfgoodrich-mar2026-promo-online-redemption-instructions.JPEG",
    "previewImage": "https://www.r2cthemes.com/Rebates/2026/bfgoodrich-mar2026-200.webp",
    "bannerImage": "https://www.r2cthemes.com/Rebates/2026/bfgoodrich-mar2026-300.webp"
  },
  {
    "brand": "MICHELIN",
    "amount": 80,
    "amountReason": "Buy 4 and qualify for an $80 Rebate",
    "amountTwo": 0,
    "amountTwoReason": "",
    "qtyRequired": 4,
    "startDate": "3/26/26 0:00",
    "endDate": "5/23/26 0:00",
    "description": "Get $80 via Visa\u00ae Reward Card or Visa\u00ae Virtual Prepaid Card after online submission on purchases of four (4) new Michelin passenger or light truck tires.",
    "pdfUrl": "https://www.r2cthemes.com/Rebates/2026/pdf/michelin-spring-mar2026-promo-online-redemption-instructions.PDF",
    "previewImage": "https://www.r2cthemes.com/Rebates/2026/michelin-mar2026-200.webp",
    "bannerImage": "https://www.r2cthemes.com/Rebates/2026/michelin-mar2026-300.webp"
  },
  {
    "brand": "FIRESTONE",
    "amount": 80,
    "amountReason": "Buy 4 and qualify for an $80 Rebate",
    "amountTwo": 0,
    "amountTwoReason": "",
    "qtyRequired": 4,
    "startDate": "4/1/26 0:00",
    "endDate": "4/30/26 0:00",
    "description": "Receive an $80 Firestone Prepaid Mastercard\u00ae with a qualifying purchase of Firestone All Season tires.",
    "pdfUrl": "https://www.r2cthemes.com/Rebates/2026/pdf/promo_allseason_fs2026_tearpad_us_noncfna.pdf",
    "previewImage": "https://www.r2cthemes.com/Rebates/2026/firestone-apr2026-200.webp",
    "bannerImage": "https://www.r2cthemes.com/Rebates/2026/firestone-apr2026-300.webp"
  },
  {
    "brand": "BFGOODRICH",
    "amount": 80,
    "amountReason": "Buy 4 and qualify for an $80 Rebate",
    "amountTwo": 0,
    "amountTwoReason": "",
    "qtyRequired": 4,
    "startDate": "5/24/26 0:00",
    "endDate": "5/31/26 0:00",
    "description": "Get $80 via Visa\u00ae Reward Card or Visa\u00ae Virtual Account after online submission on purchases of four (4) new BFGoodrich passenger or light truck tires.",
    "pdfUrl": "https://www.r2cthemes.com/Rebates/2026/pdf/bfgoodrich-may2026-promo-online-redemption-instructions.pdf",
    "previewImage": "https://www.r2cthemes.com/Rebates/2026/bfgoodrich-may2026-200.webp",
    "bannerImage": "https://www.r2cthemes.com/Rebates/2026/bfgoodrich-may2026-300.webp"
  },
  {
    "brand": "MICHELIN",
    "amount": 80,
    "amountReason": "Buy 4 and qualify for an $80 Rebate",
    "amountTwo": 0,
    "amountTwoReason": "",
    "qtyRequired": 4,
    "startDate": "5/24/26 0:00",
    "endDate": "5/31/26 0:00",
    "description": "Get $80 via Visa\u00ae Reward Card or Visa\u00ae Virtual Prepaid Card after online submission on purchases of four (4) new Michelin passenger or light truck tires.",
    "pdfUrl": "https://www.r2cthemes.com/Rebates/2026/pdf/michelin-spring-may2026-promo-online-redemption-instructions.pdf",
    "previewImage": "https://www.r2cthemes.com/Rebates/2026/michelin-may2026-200.webp",
    "bannerImage": "https://www.r2cthemes.com/Rebates/2026/michelin-may2026-300.webp"
  },
  {
    "brand": "COOPER",
    "amount": 70,
    "amountReason": "Buy 4 and qualify for a $70 Rebate",
    "amountTwo": 0,
    "amountTwoReason": "",
    "qtyRequired": 4,
    "startDate": "3/1/26 0:00",
    "endDate": "6/30/26 0:00",
    "description": "Get $70 back on a set of 4 select Cooper tires by online or mail-in rebate.",
    "pdfUrl": "https://www.r2cthemes.com/Rebates/2026/pdf/npp1-2026-cooper-base-rebate-form_mar-jun_final.pdf",
    "previewImage": "https://www.r2cthemes.com/Rebates/2026/cooper-mar2026-70-200.webp",
    "bannerImage": "https://www.r2cthemes.com/Rebates/2026/cooper-mar2026-70-300.webp"
  },
  {
    "brand": "GENERAL",
    "amount": 70,
    "amountReason": "Buy 4 and qualify for a $70 Rebate",
    "amountTwo": 0,
    "amountTwoReason": "",
    "qtyRequired": 4,
    "startDate": "3/1/26 0:00",
    "endDate": "4/30/26 0:00",
    "description": "Get up to $80 via prepaid card when you buy any 4 qualifying General Tire brand tires.",
    "pdfUrl": "https://www.r2cthemes.com/Rebates/2026/pdf/gt26_promo1_rebateform_gt-only.pdf",
    "previewImage": "https://www.r2cthemes.com/Rebates/2026/general-mar2026-80-200.webp",
    "bannerImage": "https://www.r2cthemes.com/Rebates/2026/general-mar2026-80-300.webp"
  },
  {
    "brand": "GOODYEAR",
    "amount": 60,
    "amountReason": "Buy 4 and qualify for a $60 Rebate",
    "amountTwo": 0,
    "amountTwoReason": "",
    "qtyRequired": 4,
    "startDate": "3/1/26 0:00",
    "endDate": "6/30/26 0:00",
    "description": "Get up to $80 back on a set of 4 select Goodyear tires by online or mail-in rebate.",
    "pdfUrl": "https://www.r2cthemes.com/Rebates/2026/pdf/npp1-2026-goodyear-base-rebate-form_mar-jun_final.pdf",
    "previewImage": "https://www.r2cthemes.com/Rebates/2026/goodyear-mar2026-80-200.webp",
    "bannerImage": "https://www.r2cthemes.com/Rebates/2026/goodyear-mar2026-80-300 copy.webp"
  },
  {
    "brand": "MILESTAR",
    "amount": 50,
    "amountReason": "Buy 4 and qualify for a $50 Rebate",
    "amountTwo": 0,
    "amountTwoReason": "",
    "qtyRequired": 4,
    "startDate": "5/1/26 0:00",
    "endDate": "6/30/26 0:00",
    "description": "Get a $50 consumer rebate when you buy one set of four new Interceptor AS810, Weatherguard AS710, or Patagonia A/T Pro tires.",
    "pdfUrl": "https://milestarrebates.com/Home.aspx",
    "previewImage": "https://www.r2cthemes.com/Rebates/2026/milestar-may2026-200.webp",
    "bannerImage": "https://www.r2cthemes.com/Rebates/2026/milestar-may2026-300.webp"
  },
  {
    "brand": "LAUFENN",
    "amount": 40,
    "amountReason": "Buy 4 and qualify for a $40 Rebate",
    "amountTwo": 0,
    "amountTwoReason": "",
    "qtyRequired": 4,
    "startDate": "4/20/26 0:00",
    "endDate": "5/31/26 0:00",
    "description": "Get up to a $70 rebate when you purchase 4 select Laufenn Tires.",
    "pdfUrl": "https://hankookrebates.com/",
    "previewImage": "https://www.r2cthemes.com/Rebates/2026/laufenn-apr2026-200.webp",
    "bannerImage": "https://www.r2cthemes.com/Rebates/2026/laufenn-apr2026-300.webp"
  }
];
